#!/usr/bin/env python3
"""
Price scheduled matches from the joint player + team correlated NB2 model.

Inputs from NBBoard_joint.py
----------------------------
    NB2_player_leaderboardsept_team_joint.csv
    NB2_team_ratingssept_joint.csv
    NB2_stream_effectssept_team_joint.csv
    NB2_joint_calibrationsept_team.csv

Mean score model
----------------
    log(mu_1) = beta0 + stream_effect + player_attack_1 + team_attack_1\n                - player_defense_2 - team_defense_2
    log(mu_2) = beta0 + stream_effect + player_attack_2 + team_attack_2\n                - player_defense_1 - team_defense_1

Equivalently, with
    skill_i = (attack_i + defense_i)/2
    pace_i  = (attack_i - defense_i)/2

    log(mu_1) = beta0 + stream + pace_1 + pace_2 + skill_1 - skill_2
    log(mu_2) = beta0 + stream + pace_1 + pace_2 - skill_1 + skill_2

so the two gamers' pace tendencies interact directly in BOTH expected scores.

Joint score distribution
------------------------
After stream-level variance calibration, effective alpha is

    alpha_i* = Dispersion_Scale_stream * alpha_i

and r_i = 1/alpha_i*.  A shared Gamma game factor is used:

    k  = Shared_Gamma_Fraction_stream * min(r_1, r_2)
    U  ~ Gamma(k, 1)
    V1 ~ Gamma(r_1-k, 1)
    V2 ~ Gamma(r_2-k, 1)

    lambda_1 = (mu_1/r_1) * (U + V1)
    lambda_2 = (mu_2/r_2) * (U + V2)
    Y1 | lambda_1 ~ Poisson(lambda_1)
    Y2 | lambda_2 ~ Poisson(lambda_2)

Each score therefore remains exactly NB2 marginally, but the two scores have
positive covariance generated by the shared U factor.

Outputs
-------
1) Match summary CSV:
   expected points, total, margin, score covariance/correlation, total/margin SD,
   fair moneyline, fair spread line, fair total line.
2) Spread ladder CSV around the fair line.
3) Totals ladder CSV around the fair line.

Moneyline ties are split 50/50, appropriate when a later OT mechanism forces a
winner. Spread/total pushes are handled as voids when converting to fair odds.

Example
-------
python3 NB2_joint_schedule_predict.py \
    --schedule eamfschedule.csv \
    --n-sims 250000

With 9% proportional overround:
python3 NB2_joint_schedule_predict.py \
    --schedule eamfschedule.csv \
    --n-sims 250000 \
    --overround 0.09
"""

import argparse
import math
import zlib

import numpy as np
import pandas as pd


def parse_args():
    p = argparse.ArgumentParser(description="Price a schedule from the joint correlated NB2 model.")
    p.add_argument("--schedule", default="eamfschedule.csv", help="Schedule CSV")
    p.add_argument("--leaderboard", default="NB2_player_leaderboardsept_team_joint.csv", help="Player leaderboard CSV")
    p.add_argument("--teams", default="NB2_team_ratingssept_joint.csv", help="Team attack/defence ratings CSV")
    p.add_argument("--streams", default="NB2_stream_effectssept_team_joint.csv", help="Stream effects CSV")
    p.add_argument("--joint", default="NB2_joint_calibrationsept_team.csv", help="Joint variance/covariance calibration CSV")
    p.add_argument("--output", default="NB2_joint_schedule_predictions.csv", help="Match summary output CSV")
    p.add_argument("--spread-output", default="NB2_joint_spread_markets.csv", help="Spread ladder output CSV")
    p.add_argument("--totals-output", default="NB2_joint_total_markets.csv", help="Totals ladder output CSV")

    p.add_argument("--p1-col", default="Player 1 Name")
    p.add_argument("--p2-col", default="Player 2 Name")
    p.add_argument("--p1-team-col", default="Player 1 Team")
    p.add_argument("--p2-team-col", default="Player 2 Team")
    p.add_argument("--stream-col", default=None,
                   help="Optional schedule stream column. Otherwise infer from Current_Stream.")
    p.add_argument("--default-stream", type=float, default=None,
                   help="Fallback stream if current streams disagree/missing.")

    p.add_argument("--n-sims", type=int, default=250000,
                   help="Joint Monte Carlo draws per match. Default 250000 (~0.1pp ML MC error near 50%%).")
    p.add_argument("--seed", type=int, default=260909,
                   help="Base random seed. Match id is mixed in so output is stable to row order.")
    p.add_argument("--overround", type=float, default=0.0,
                   help="Optional proportional two-way overround, e.g. 0.09 for 9%%.")
    p.add_argument("--min-prob", type=float, default=1e-9)

    p.add_argument("--line-window", type=float, default=10.0,
                   help="Generate spread/total ladders +/- this many points around the simulated median.")
    p.add_argument("--line-step", type=float, default=0.5,
                   help="Market line spacing. Default 0.5 points.")
    return p.parse_args()


def canonical_player(x):
    if pd.isna(x):
        return None
    s = str(x).strip()
    if not s or s.lower() in {"nan", "none", "cancelled", "canceled", "-"}:
        return None
    return s.upper()


def canonical_team(x):
    if pd.isna(x):
        return None
    s = str(x).strip()
    if not s or s.lower() in {"nan", "none", "cancelled", "canceled", "-"}:
        return None
    return s.casefold()


def canonical_stream(x):
    if pd.isna(x):
        return None
    s = str(x).strip()
    if not s:
        return None
    if s.upper() == "GLOBAL":
        return "GLOBAL"
    try:
        f = float(s)
        if f.is_integer():
            return int(f)
        return f
    except (TypeError, ValueError):
        return s


def recover_beta0(streams):
    x = streams[["Stream_Log_Scoring_Effect", "Model_Baseline_Mean_Score"]].dropna().copy()
    if x.empty:
        raise ValueError("No valid stream rows available to recover beta0.")
    vals = np.log(x["Model_Baseline_Mean_Score"].astype(float).to_numpy()) \
           - x["Stream_Log_Scoring_Effect"].astype(float).to_numpy()
    beta0 = float(np.mean(vals))
    spread = float(np.max(vals) - np.min(vals)) if len(vals) > 1 else 0.0
    if spread > 1e-6:
        print(f"WARNING: reconstructed beta0 varies by {spread:.3g}; using mean {beta0:.8f}.")
    return beta0


def stable_match_seed(base_seed, match_id, row_number):
    key = str(match_id) if match_id is not None and not pd.isna(match_id) else f"ROW_{row_number}"
    crc = zlib.crc32(key.encode("utf-8")) & 0xFFFFFFFF
    return (int(base_seed) + crc) % (2**32 - 1)


def safe_odds(prob, min_prob):
    return 1.0 / max(float(prob), min_prob)


def priced_probability(fair_prob, overround):
    # Proportional probability loading. Clamp only to avoid nonsensical decimal odds
    # if an extreme favourite plus a very large requested overround exceeds 100%.
    return min(max(float(fair_prob) * (1.0 + overround), 1e-12), 0.999999999)


def joint_moments(mu1, alpha1, mu2, alpha2, shared_fraction):
    var1 = mu1 + alpha1 * mu1 * mu1
    var2 = mu2 + alpha2 * mu2 * mu2
    cov = shared_fraction * mu1 * mu2 * min(alpha1, alpha2)
    corr = cov / math.sqrt(var1 * var2) if var1 > 0 and var2 > 0 else np.nan
    margin_var = max(var1 + var2 - 2.0 * cov, 0.0)
    total_var = max(var1 + var2 + 2.0 * cov, 0.0)
    return var1, var2, cov, corr, margin_var, total_var


def joint_nb2_draws(mu1, alpha1, mu2, alpha2, shared_fraction, n_sims, rng):
    """Gamma-Poisson construction with exact NB2 marginals and positive covariance."""
    if mu1 <= 0 or mu2 <= 0 or alpha1 <= 0 or alpha2 <= 0:
        raise ValueError("mu and effective alpha must be positive")
    if not (0 <= shared_fraction < 1):
        raise ValueError("shared_fraction must be in [0,1)")

    r1 = 1.0 / alpha1
    r2 = 1.0 / alpha2
    k = shared_fraction * min(r1, r2)
    idio1 = r1 - k
    idio2 = r2 - k

    if k > 1e-12:
        common = rng.gamma(shape=k, scale=1.0, size=n_sims)
    else:
        common = np.zeros(n_sims, dtype=float)
    v1 = rng.gamma(shape=max(idio1, 1e-12), scale=1.0, size=n_sims)
    v2 = rng.gamma(shape=max(idio2, 1e-12), scale=1.0, size=n_sims)

    lam1 = (mu1 / r1) * (common + v1)
    lam2 = (mu2 / r2) * (common + v2)
    s1 = rng.poisson(lam1)
    s2 = rng.poisson(lam2)
    return s1.astype(np.int16, copy=False), s2.astype(np.int16, copy=False), k


def fair_with_push(win_prob, push_prob):
    """Break-even probability/odds when a push returns stake."""
    nonpush = 1.0 - push_prob
    if nonpush <= 0:
        return np.nan, np.nan
    p_cond = win_prob / nonpush
    odds = nonpush / win_prob if win_prob > 0 else np.inf
    return p_cond, odds


def line_grid(center, window, step):
    lo = math.floor((center - window) / step) * step
    hi = math.ceil((center + window) / step) * step
    n = int(round((hi - lo) / step))
    vals = lo + step * np.arange(n + 1)
    return np.round(vals, 8)


def price_spread_ladder(margins, center_handicap, window, step, overround, min_prob,
                        base_fields):
    rows = []
    best = None
    for h in line_grid(center_handicap, window, step):
        adj = margins + h
        p1_win = float(np.mean(adj > 0))
        push = float(np.mean(adj == 0))
        p2_win = float(np.mean(adj < 0))
        p1_np, p1_odds = fair_with_push(p1_win, push)
        p2_np, p2_odds = fair_with_push(p2_win, push)
        if np.isfinite(p1_np):
            p1_priced = priced_probability(p1_np, overround)
            p2_priced = priced_probability(p2_np, overround)
        else:
            p1_priced = p2_priced = np.nan
        row = {
            **base_fields,
            "P1_Handicap": float(h),
            "P1_Cover_Prob": p1_win,
            "Push_Prob": push,
            "P2_Cover_Prob": p2_win,
            "P1_Fair_NoPush_Prob": p1_np,
            "P2_Fair_NoPush_Prob": p2_np,
            "P1_Fair_Decimal_Odds": p1_odds,
            "P2_Fair_Decimal_Odds": p2_odds,
            "P1_Priced_Prob": p1_priced,
            "P2_Priced_Prob": p2_priced,
            "P1_Priced_Decimal_Odds": safe_odds(p1_priced, min_prob) if np.isfinite(p1_priced) else np.nan,
            "P2_Priced_Decimal_Odds": safe_odds(p2_priced, min_prob) if np.isfinite(p2_priced) else np.nan,
            "Applied_Overround": overround,
        }
        rows.append(row)
        if np.isfinite(p1_np):
            dist = abs(p1_np - 0.5)
            if best is None or dist < best[0]:
                best = (dist, float(h), p1_np, push)
    return rows, best


def price_total_ladder(totals, center_total, window, step, overround, min_prob,
                       base_fields):
    rows = []
    best = None
    for line in line_grid(center_total, window, step):
        over = float(np.mean(totals > line))
        push = float(np.mean(totals == line))
        under = float(np.mean(totals < line))
        over_np, over_odds = fair_with_push(over, push)
        under_np, under_odds = fair_with_push(under, push)
        if np.isfinite(over_np):
            over_priced = priced_probability(over_np, overround)
            under_priced = priced_probability(under_np, overround)
        else:
            over_priced = under_priced = np.nan
        row = {
            **base_fields,
            "Total_Line": float(line),
            "Over_Prob": over,
            "Push_Prob": push,
            "Under_Prob": under,
            "Over_Fair_NoPush_Prob": over_np,
            "Under_Fair_NoPush_Prob": under_np,
            "Over_Fair_Decimal_Odds": over_odds,
            "Under_Fair_Decimal_Odds": under_odds,
            "Over_Priced_Prob": over_priced,
            "Under_Priced_Prob": under_priced,
            "Over_Priced_Decimal_Odds": safe_odds(over_priced, min_prob) if np.isfinite(over_priced) else np.nan,
            "Under_Priced_Decimal_Odds": safe_odds(under_priced, min_prob) if np.isfinite(under_priced) else np.nan,
            "Applied_Overround": overround,
        }
        rows.append(row)
        if np.isfinite(over_np):
            dist = abs(over_np - 0.5)
            if best is None or dist < best[0]:
                best = (dist, float(line), over_np, push)
    return rows, best


def main():
    args = parse_args()
    if args.n_sims < 1000:
        raise ValueError("--n-sims must be at least 1000")
    if args.overround < 0:
        raise ValueError("--overround must be >= 0")
    if args.line_step <= 0 or args.line_window < 0:
        raise ValueError("--line-step must be >0 and --line-window must be >=0")

    schedule = pd.read_csv(args.schedule)
    lb = pd.read_csv(args.leaderboard)
    teams = pd.read_csv(args.teams)
    streams = pd.read_csv(args.streams)
    joint = pd.read_csv(args.joint)

    for c in [args.p1_col, args.p2_col]:
        if c not in schedule.columns:
            raise ValueError(f"Schedule missing player column: {c}")
    for c in [args.p1_team_col, args.p2_team_col]:
        if c not in schedule.columns:
            raise ValueError(f"Schedule missing team column: {c}")

    req_lb = {"Player", "Attack", "Defense", "Alpha", "Current_Stream"}
    missing = req_lb - set(lb.columns)
    if missing:
        raise ValueError(f"Leaderboard missing columns: {sorted(missing)}")
    req_team = {"Team", "Attack", "Defense"}
    missing = req_team - set(teams.columns)
    if missing:
        raise ValueError(f"Team ratings file missing columns: {sorted(missing)}")
    req_stream = {"Stream", "Stream_Log_Scoring_Effect", "Model_Baseline_Mean_Score"}
    missing = req_stream - set(streams.columns)
    if missing:
        raise ValueError(f"Stream effects file missing columns: {sorted(missing)}")
    req_joint = {"Stream", "Dispersion_Scale", "Shared_Gamma_Fraction"}
    missing = req_joint - set(joint.columns)
    if missing:
        raise ValueError(f"Joint calibration file missing columns: {sorted(missing)}")

    beta0 = recover_beta0(streams)

    lb = lb.copy()
    lb["_player"] = lb["Player"].map(canonical_player)
    if lb["_player"].duplicated().any():
        dups = lb.loc[lb["_player"].duplicated(keep=False), "Player"].tolist()
        raise ValueError(f"Duplicate player rows in leaderboard: {dups}")
    player_map = lb.set_index("_player").to_dict("index")

    teams = teams.copy()
    teams["_team"] = teams["Team"].map(canonical_team)
    if teams["_team"].duplicated().any():
        dups = teams.loc[teams["_team"].duplicated(keep=False), "Team"].tolist()
        raise ValueError(f"Duplicate team rows in team ratings: {dups}")
    team_map = teams.set_index("_team").to_dict("index")

    streams = streams.copy()
    streams["_stream"] = streams["Stream"].map(canonical_stream)
    stream_map = streams.set_index("_stream")["Stream_Log_Scoring_Effect"].astype(float).to_dict()

    joint = joint.copy()
    joint["_stream"] = joint["Stream"].map(canonical_stream)
    joint_map = joint.set_index("_stream")[["Dispersion_Scale", "Shared_Gamma_Fraction"]].to_dict("index")
    global_joint = joint_map.get("GLOBAL")

    summary_rows = []
    spread_rows = []
    total_rows = []
    priced = 0
    flagged = 0

    for row_number, src in schedule.iterrows():
        out = src.to_dict()
        p1_name = canonical_player(src.get(args.p1_col))
        p2_name = canonical_player(src.get(args.p2_col))
        p1_team = canonical_team(src.get(args.p1_team_col))
        p2_team = canonical_team(src.get(args.p2_team_col))
        match_id = src.get("Match Id", row_number)

        pred = {
            "Prediction_Status": None,
            "Model_Stream": np.nan,
            "Dispersion_Scale": np.nan,
            "Shared_Gamma_Fraction": np.nan,
            "Shared_Gamma_Shape_k": np.nan,
            "P1_Attack": np.nan,
            "P1_Defense": np.nan,
            "P1_Skill_Log_Component": np.nan,
            "P1_Pace_Log_Component": np.nan,
            "P1_Base_Alpha": np.nan,
            "P1_Effective_Alpha": np.nan,
            "P2_Attack": np.nan,
            "P2_Defense": np.nan,
            "P2_Skill_Log_Component": np.nan,
            "P2_Pace_Log_Component": np.nan,
            "P2_Base_Alpha": np.nan,
            "P2_Effective_Alpha": np.nan,
            "Matchup_Pace_Log_Effect": np.nan,
            "Matchup_Pace_Multiplier": np.nan,
            "Pred_P1_Points": np.nan,
            "Pred_P2_Points": np.nan,
            "Pred_Total_Points": np.nan,
            "Pred_P1_Margin": np.nan,
            "Pred_P1_Score_SD": np.nan,
            "Pred_P2_Score_SD": np.nan,
            "Pred_Score_Covariance": np.nan,
            "Pred_Score_Correlation": np.nan,
            "Pred_Margin_SD": np.nan,
            "Pred_Total_SD": np.nan,
            "P1_Regulation_Win_Prob": np.nan,
            "Regulation_Tie_Prob": np.nan,
            "P2_Regulation_Win_Prob": np.nan,
            "P1_Fair_ML_Prob": np.nan,
            "P2_Fair_ML_Prob": np.nan,
            "P1_Fair_Decimal_Odds": np.nan,
            "P2_Fair_Decimal_Odds": np.nan,
            "P1_Priced_Prob": np.nan,
            "P2_Priced_Prob": np.nan,
            "P1_Priced_Decimal_Odds": np.nan,
            "P2_Priced_Decimal_Odds": np.nan,
            "Fair_P1_Handicap": np.nan,
            "Fair_P1_Cover_Prob_At_Line": np.nan,
            "Fair_Total_Line": np.nan,
            "Fair_Over_Prob_At_Line": np.nan,
            "Sim_Median_Margin": np.nan,
            "Sim_Median_Total": np.nan,
            "ML_MC_SE": np.nan,
            "N_Sims": args.n_sims,
            "Applied_Overround": args.overround,
        }

        if p1_name is None and p2_name is None:
            text = " ".join(str(v) for v in src.values if pd.notna(v)).lower()
            pred["Prediction_Status"] = "CANCELLED" if "cancel" in text else "NON_MATCH_ROW"
            summary_rows.append({**out, **pred})
            continue
        if p1_name is None or p2_name is None:
            pred["Prediction_Status"] = "INVALID_PLAYERS"
            flagged += 1
            summary_rows.append({**out, **pred})
            continue
        if p1_name not in player_map or p2_name not in player_map:
            missing_players = [p for p in [p1_name, p2_name] if p not in player_map]
            pred["Prediction_Status"] = "UNKNOWN_PLAYER:" + "|".join(missing_players)
            flagged += 1
            summary_rows.append({**out, **pred})
            continue
        if p1_team is None or p2_team is None:
            pred["Prediction_Status"] = "INVALID_TEAMS"
            flagged += 1
            summary_rows.append({**out, **pred})
            continue
        if p1_team not in team_map or p2_team not in team_map:
            missing_teams = [str(src.get(args.p1_team_col)) if p1_team not in team_map else None,
                             str(src.get(args.p2_team_col)) if p2_team not in team_map else None]
            missing_teams = [x for x in missing_teams if x is not None]
            pred["Prediction_Status"] = "UNKNOWN_TEAM:" + "|".join(missing_teams)
            flagged += 1
            summary_rows.append({**out, **pred})
            continue

        r1row = player_map[p1_name]
        r2row = player_map[p2_name]
        t1row = team_map[p1_team]
        t2row = team_map[p2_team]

        # Infer model stream.
        model_stream = None
        if args.stream_col and args.stream_col in schedule.columns:
            model_stream = canonical_stream(src.get(args.stream_col))
        else:
            s1 = canonical_stream(r1row.get("Current_Stream"))
            s2 = canonical_stream(r2row.get("Current_Stream"))
            if s1 is not None and s1 == s2:
                model_stream = s1
            elif s1 is not None and s2 is None:
                model_stream = s1
            elif s2 is not None and s1 is None:
                model_stream = s2
            elif args.default_stream is not None:
                model_stream = canonical_stream(args.default_stream)
            else:
                pred["Prediction_Status"] = f"STREAM_MISMATCH:{s1}|{s2}"
                flagged += 1
                summary_rows.append({**out, **pred})
                continue

        if model_stream not in stream_map:
            pred["Prediction_Status"] = f"UNKNOWN_STREAM:{model_stream}"
            flagged += 1
            summary_rows.append({**out, **pred})
            continue

        jcal = joint_map.get(model_stream, global_joint)
        if jcal is None:
            pred["Prediction_Status"] = f"NO_JOINT_CALIBRATION:{model_stream}"
            flagged += 1
            summary_rows.append({**out, **pred})
            continue

        attack1 = float(r1row["Attack"])
        defense1 = float(r1row["Defense"])
        attack2 = float(r2row["Attack"])
        defense2 = float(r2row["Defense"])
        team_attack1 = float(t1row["Attack"])
        team_defense1 = float(t1row["Defense"])
        team_attack2 = float(t2row["Attack"])
        team_defense2 = float(t2row["Defense"])
        combined_attack1 = attack1 + team_attack1
        combined_defense1 = defense1 + team_defense1
        combined_attack2 = attack2 + team_attack2
        combined_defense2 = defense2 + team_defense2
        skill1 = 0.5 * (combined_attack1 + combined_defense1)
        skill2 = 0.5 * (combined_attack2 + combined_defense2)
        pace1 = 0.5 * (combined_attack1 - combined_defense1)
        pace2 = 0.5 * (combined_attack2 - combined_defense2)
        base_alpha1 = float(r1row["Alpha"])
        base_alpha2 = float(r2row["Alpha"])
        dispersion_scale = float(jcal["Dispersion_Scale"])
        shared_fraction = float(jcal["Shared_Gamma_Fraction"])
        alpha1 = dispersion_scale * base_alpha1
        alpha2 = dispersion_scale * base_alpha2
        stream_eff = float(stream_map[model_stream])

        eta1 = beta0 + stream_eff + attack1 + team_attack1 - defense2 - team_defense2
        eta2 = beta0 + stream_eff + attack2 + team_attack2 - defense1 - team_defense1
        mu1 = float(np.exp(np.clip(eta1, -15, 15)))
        mu2 = float(np.exp(np.clip(eta2, -15, 15)))

        var1, var2, cov, corr, margin_var, total_var = joint_moments(
            mu1, alpha1, mu2, alpha2, shared_fraction
        )

        seed = stable_match_seed(args.seed, match_id, row_number)
        rng = np.random.default_rng(seed)
        s1draw, s2draw, k = joint_nb2_draws(
            mu1, alpha1, mu2, alpha2, shared_fraction, args.n_sims, rng
        )
        margins = s1draw.astype(np.int32) - s2draw.astype(np.int32)
        totals = s1draw.astype(np.int32) + s2draw.astype(np.int32)

        p1_reg = float(np.mean(margins > 0))
        p_tie = float(np.mean(margins == 0))
        p2_reg = float(np.mean(margins < 0))
        p1_fair = p1_reg + 0.5 * p_tie
        p2_fair = p2_reg + 0.5 * p_tie
        p1_priced = priced_probability(p1_fair, args.overround)
        p2_priced = priced_probability(p2_fair, args.overround)

        median_margin = float(np.median(margins))
        median_total = float(np.median(totals))
        center_handicap = -median_margin
        base_fields = {
            "Match Id": match_id,
            args.p1_col: src.get(args.p1_col),
            args.p2_col: src.get(args.p2_col),
            "Model_Stream": model_stream,
            args.p1_team_col: src.get(args.p1_team_col),
            args.p2_team_col: src.get(args.p2_team_col),
        }

        srows, best_spread = price_spread_ladder(
            margins, center_handicap, args.line_window, args.line_step,
            args.overround, args.min_prob, base_fields
        )
        trows, best_total = price_total_ladder(
            totals, median_total, args.line_window, args.line_step,
            args.overround, args.min_prob, base_fields
        )
        spread_rows.extend(srows)
        total_rows.extend(trows)

        pred.update({
            "Prediction_Status": "OK",
            "Model_Stream": model_stream,
            "Dispersion_Scale": dispersion_scale,
            "Shared_Gamma_Fraction": shared_fraction,
            "Shared_Gamma_Shape_k": k,
            "P1_Team": src.get(args.p1_team_col),
            "P2_Team": src.get(args.p2_team_col),
            "P1_Player_Attack": attack1,
            "P1_Player_Defense": defense1,
            "P1_Team_Attack": team_attack1,
            "P1_Team_Defense": team_defense1,
            "P1_Combined_Attack": combined_attack1,
            "P1_Combined_Defense": combined_defense1,
            "P2_Player_Attack": attack2,
            "P2_Player_Defense": defense2,
            "P2_Team_Attack": team_attack2,
            "P2_Team_Defense": team_defense2,
            "P2_Combined_Attack": combined_attack2,
            "P2_Combined_Defense": combined_defense2,
            "P1_Attack": combined_attack1,
            "P1_Defense": combined_defense1,
            "P1_Skill_Log_Component": skill1,
            "P1_Pace_Log_Component": pace1,
            "P1_Base_Alpha": base_alpha1,
            "P1_Effective_Alpha": alpha1,
            "P2_Attack": combined_attack2,
            "P2_Defense": combined_defense2,
            "P2_Skill_Log_Component": skill2,
            "P2_Pace_Log_Component": pace2,
            "P2_Base_Alpha": base_alpha2,
            "P2_Effective_Alpha": alpha2,
            "Matchup_Pace_Log_Effect": pace1 + pace2,
            "Matchup_Pace_Multiplier": math.exp(pace1 + pace2),
            "Pred_P1_Points": mu1,
            "Pred_P2_Points": mu2,
            "Pred_Total_Points": mu1 + mu2,
            "Pred_P1_Margin": mu1 - mu2,
            "Pred_P1_Score_SD": math.sqrt(var1),
            "Pred_P2_Score_SD": math.sqrt(var2),
            "Pred_Score_Covariance": cov,
            "Pred_Score_Correlation": corr,
            "Pred_Margin_SD": math.sqrt(margin_var),
            "Pred_Total_SD": math.sqrt(total_var),
            "P1_Regulation_Win_Prob": p1_reg,
            "Regulation_Tie_Prob": p_tie,
            "P2_Regulation_Win_Prob": p2_reg,
            "P1_Fair_ML_Prob": p1_fair,
            "P2_Fair_ML_Prob": p2_fair,
            "P1_Fair_Decimal_Odds": safe_odds(p1_fair, args.min_prob),
            "P2_Fair_Decimal_Odds": safe_odds(p2_fair, args.min_prob),
            "P1_Priced_Prob": p1_priced,
            "P2_Priced_Prob": p2_priced,
            "P1_Priced_Decimal_Odds": safe_odds(p1_priced, args.min_prob),
            "P2_Priced_Decimal_Odds": safe_odds(p2_priced, args.min_prob),
            "Fair_P1_Handicap": best_spread[1] if best_spread else np.nan,
            "Fair_P1_Cover_Prob_At_Line": best_spread[2] if best_spread else np.nan,
            "Fair_Total_Line": best_total[1] if best_total else np.nan,
            "Fair_Over_Prob_At_Line": best_total[2] if best_total else np.nan,
            "Sim_Median_Margin": median_margin,
            "Sim_Median_Total": median_total,
            "ML_MC_SE": math.sqrt(max(p1_fair * (1.0 - p1_fair), 0.0) / args.n_sims),
        })
        summary_rows.append({**out, **pred})
        priced += 1

    summary = pd.DataFrame(summary_rows)
    spreads = pd.DataFrame(spread_rows)
    totals_df = pd.DataFrame(total_rows)
    summary.to_csv(args.output, index=False)
    spreads.to_csv(args.spread_output, index=False)
    totals_df.to_csv(args.totals_output, index=False)

    print("\nJOINT NB2 PLAYER + TEAM SCHEDULE PRICING")
    print("=" * 76)
    print(f"Recovered beta0:          {beta0:.8f}  baseline={math.exp(beta0):.4f}")
    print(f"Schedule rows:            {len(schedule):,}")
    print(f"Priced matches:           {priced:,}")
    print(f"Flagged rows:             {flagged:,}")
    print(f"Joint draws per match:    {args.n_sims:,}")
    print(f"Applied overround:        {args.overround:.4f}")
    print(f"Summary output:           {args.output}")
    print(f"Spread ladder output:     {args.spread_output}")
    print(f"Totals ladder output:     {args.totals_output}")

    ok = summary[summary["Prediction_Status"] == "OK"]
    if not ok.empty:
        print(f"\nFair ML P1 range:         {ok['P1_Fair_ML_Prob'].min():.4f} -> {ok['P1_Fair_ML_Prob'].max():.4f}")
        print(f"Predicted margin SD:      {ok['Pred_Margin_SD'].min():.3f} -> {ok['Pred_Margin_SD'].max():.3f}")
        print(f"Predicted score corr:     {ok['Pred_Score_Correlation'].min():.3f} -> {ok['Pred_Score_Correlation'].max():.3f}")
        show = [c for c in [
            "Match Id", args.p1_col, args.p2_col, "Model_Stream",
            "Pred_P1_Points", "Pred_P2_Points", "Pred_Total_Points", "Pred_P1_Margin",
            "Pred_Score_Correlation", "Pred_Margin_SD",
            "P1_Fair_ML_Prob", "P2_Fair_ML_Prob",
            "P1_Fair_Decimal_Odds", "P2_Fair_Decimal_Odds",
            "Fair_P1_Handicap", "Fair_Total_Line"
        ] if c in ok.columns]
        print("\nFirst priced matches:")
        print(ok[show].head(20).to_string(index=False, float_format=lambda x: f"{x:.4f}"))


if __name__ == "__main__":
    main()
